# 数据分析
数据收集--数据清洗--数据分析--数据可视化

## 数据的导入和导出

In [5]:
import pandas as pd
url = "https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv"
df = pd.read_csv(url)

print(type(df))
print(df.tail())
print(df['Age'].mean())

<class 'pandas.DataFrame'>
     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   NaN        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female   NaN      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q
29.69911764705882

In [12]:
# json
df.to_csv("titanic.csv",index=False)
df=pd.read_csv("titanic.csv")
df.head()

#把df保存为json文件
df.to_json("titanic.json",orient="records")

#读取json文件
import json
with open('titanic.json') as f:
    data = json.load(f)

#转回DataFrame看
import pandas as pd
df2=pd.DataFrame(data)
df2.head()
# print(type(df2))

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 缺失值的处理

In [40]:
# nan:not a number
import pandas as pd
import numpy as np
s=pd.Series([1,2,np.nan,None,pd.NA])
df=pd.DataFrame([[1,pd.NA,2],[2,3,5],[None,4,6]],columns=['A','B','C'])
print(s)
# 查看是否是缺失值
print(s.isna())
print(s.isnull())
print(df.isna())
print(df.isnull())
print(df.isna().sum()) # 查看缺失值的个数
print(s.isnull().sum())
print('-'*30)

#剔除缺失值
print(s.dropna())
print('-'*30)
print(df.dropna())  #直接把一行删除
print('-'*30)
print(df.dropna(how='all'))  #全部是缺失值才删除
print('-'*30)
print(df.dropna(thresh=2)) # 如果至少有n个值不是缺失值就保留
print('-'*30)
print(df.dropna(axis=1)) # 剔除一整列的记录
print('-'*30)
print(df.dropna(subset=['A'])) #如果某列有缺失值，则删除这一行

#填充缺失值
df=pd.read_csv('titanic.csv')
df.tail()
df.isna().sum(axis=0)
df.head()
print(df.fillna({'Age':0}).tail()) #使用字典来填充
print('-'*30)
print(df.fillna(df[['Age']].mean()).tail()) #使用统计值来填充缺失值
print('-'*30)
print(df.ffill().tail()) #front
print('-'*30)
print(df.bfill().tail()) #behind

0       1
1       2
2     NaN
3    None
4    <NA>
dtype: object
0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool
       A      B      C
0  False   True  False
1  False  False  False
2   True  False  False
       A      B      C
0  False   True  False
1  False  False  False
2   True  False  False
A    1
B    1
C    0
dtype: int64
3
------------------------------
0    1
1    2
dtype: object
------------------------------
     A  B  C
1  2.0  3  5
------------------------------
     A     B  C
0  1.0  <NA>  2
1  2.0     3  5
2  NaN     4  6
------------------------------
     A     B  C
0  1.0  <NA>  2
1  2.0     3  5
2  NaN     4  6
------------------------------
   C
0  2
1  5
2  6
------------------------------
     A     B  C
0  1.0  <NA>  2
1  2.0     3  5
     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   NaN        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female   0.0      1      2  W./C. 6607  23.45   NaN        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q
------------------------------
     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex        Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.000000      0      0      211536  13.00   NaN        S
887  female  19.000000      0      0      112053  30.00   B42        S
888  female  29.699118      1      2  W./C. 6607  23.45   NaN        S
889    male  26.000000      0      0      111369  30.00  C148        C
890    male  32.000000      0      0      370376   7.75   NaN        Q
------------------------------
     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   C50        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female  19.0      1      2  W./C. 6607  23.45   B42        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75  C148        Q
------------------------------
     PassengerId  Survived  Pclass                                      Name  \
886          887         0       2                     Montvila, Rev. Juozas
887          888         1       1              Graham, Miss. Margaret Edith
888          889         0       3  Johnston, Miss. Catherine Helen "Carrie"
889          890         1       1                     Behr, Mr. Karl Howell
890          891         0       3                       Dooley, Mr. Patrick

        Sex   Age  SibSp  Parch      Ticket   Fare Cabin Embarked
886    male  27.0      0      0      211536  13.00   B42        S
887  female  19.0      0      0      112053  30.00   B42        S
888  female  26.0      1      2  W./C. 6607  23.45  C148        S
889    male  26.0      0      0      111369  30.00  C148        C
890    male  32.0      0      0      370376   7.75   NaN        Q

## 数据类型的转换

In [60]:
### 重复数据
import pandas as pd
data={
    "name":['A','A','C','A','E','C'],
    "Age":[26,25,30,25,35,30],
    "city":['NY','NY','LA','NY','SF','LA']
}
df=pd.DataFrame(data)
print(df)
print('-'*30)
print(df.duplicated()) #一整行记录都是一样的，标记为重复，返回True
print('-'*30)
print(df.drop_duplicates()) #删除重复数据
print('-'*30)
print(df.drop_duplicates(subset=['name']))
print('-'*30)
print(df.drop_duplicates(subset=['name'],keep='last')) #保留最新记录

  name  Age city
0    A   26   NY
1    A   25   NY
2    C   30   LA
3    A   25   NY
4    E   35   SF
5    C   30   LA
------------------------------
0    False
1    False
2    False
3     True
4    False
5     True
dtype: bool
------------------------------
  name  Age city
0    A   26   NY
1    A   25   NY
2    C   30   LA
4    E   35   SF
------------------------------
  name  Age city
0    A   26   NY
2    C   30   LA
4    E   35   SF
------------------------------
  name  Age city
3    A   25   NY
4    E   35   SF
5    C   30   LA

In [67]:
### 数据转换
df=pd.read_csv('titanic.csv')
print(df)
df.dtypes

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
Cabin              str
Embarked           str
dtype: object

In [69]:
df['Fare']=df['Fare'].astype('int16')
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare             int16
Cabin              str
Embarked           str
dtype: object

In [73]:
df['Sex']=df['Sex'].astype('category')
df.Sex

0        male
1      female
2      female
3      female
4        male
        ...
886      male
887    female
888    female
889      male
890      male
Name: Sex, Length: 891, dtype: category
Categories (2, str): ['female', 'male']

In [76]:
df['is_male']=df['Sex'].map({'female':True,'male':False})
df.is_male

0      False
1       True
2       True
3       True
4      False
       ...
886    False
887     True
888     True
889    False
890    False
Name: is_male, Length: 891, dtype: category
Categories (2, bool): [True, False]

## 数据变形

In [86]:
import pandas as pd
data={
    'ID':[1,2],
    'name':['A','B'],
    'Math':[90,85],
    'English':[88,92],
    'Science':[95,89]
}
df=pd.DataFrame(data)
print(df)
print('-'*30)
print(df.T) #行列转置

   ID name  Math  English  Science
0   1    A    90       88       95
1   2    B    85       92       89
------------------------------
          0   1
ID        1   2
name      A   B
Math     90  85
English  88  92
Science  95  89

   ID name  subject  scores
0   1    A     Math      90
2   1    A  English      88
4   1    A  Science      95
1   2    B     Math      85
3   2    B  English      92
5   2    B  Science      89

In [89]:
#宽表转换成长表
df2=pd.melt(df,id_vars=['ID','name'],var_name='subject',value_name='scores')
df2.sort_values('name')
print(df2)

   ID name  subject  scores
0   1    A     Math      90
1   2    B     Math      85
2   1    A  English      88
3   2    B  English      92
4   1    A  Science      95
5   2    B  Science      89

In [93]:
#长表转宽表
df3=pd.pivot(df2,index=['ID','name'],columns='subject',values='scores')
print(df3)

subject  English  Math  Science
ID name
1  A          88    90       95
2  B          92    85       89

In [104]:
data={
    'ID':[1,2],
    'name':['A C','B C'],
    'Math':[90,85],
    'English':[88,92],
    'Science':[95,89]
}
df=pd.DataFrame(data)
#分列
df[['first','last']]=df['name'].str.split(" ",expand=True)
print(df)

   ID name  Math  English  Science first last
0   1  A C    90       88       95     A    C
1   2  B C    85       92       89     B    C

In [108]:
data = {
    "person_id": [1,2,3,4],
    "blood_pressure": ["120/80","130/85","115/75","142/90"]
}
df = pd.DataFrame(data)
print(df)
print('-'*30)
df = df[['person_id','blood_pressure']]
df[['high','low']] = df['blood_pressure'].str.split("/", expand=True)
print(df)

   person_id blood_pressure
0          1         120/80
1          2         130/85
2          3         115/75
3          4         142/90
------------------------------
   person_id blood_pressure high low
0          1         120/80  120  80
1          2         130/85  130  85
2          3         115/75  115  75
3          4         142/90  142  90

## 数据分箱

In [124]:
#pd.cut(x,bins,labels)
import pandas as pd
df=pd.read_csv('titanic.csv')
print(df.head(10))

   PassengerId  Survived  Pclass  \
0            1         0       3
1            2         1       1
2            3         1       3
3            4         1       1
4            5         0       3
5            6         0       3
6            7         0       1
7            8         0       3
8            9         1       3
9           10         1       2

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                             Heikkinen, Miss. Laina  female  26.0      0
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                           Allen, Mr. William Henry    male  35.0      0
5                                   Moran, Mr. James    male   NaN      0
6                            McCarthy, Mr. Timothy J    male  54.0      0
7                     Palsson, Master. Gosta Leonard    male   2.0      3
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0
9                Nasser, Mrs. Nicholas (Adele Achem)  female  14.0      1

   Parch            Ticket     Fare Cabin Embarked
0      0         A/5 21171   7.2500   NaN        S
1      0          PC 17599  71.2833   C85        C
2      0  STON/O2. 3101282   7.9250   NaN        S
3      0            113803  53.1000  C123        S
4      0            373450   8.0500   NaN        S
5      0            330877   8.4583   NaN        Q
6      0             17463  51.8625   E46        S
7      1            349909  21.0750   NaN        S
8      2            347742  11.1333   NaN        S
9      0            237736  30.0708   NaN        C

In [125]:
df1=df.head(10)[['PassengerId','Fare']]
print(df1)

   PassengerId     Fare
0            1   7.2500
1            2  71.2833
2            3   7.9250
3            4  53.1000
4            5   8.0500
5            6   8.4583
6            7  51.8625
7            8  21.0750
8            9  11.1333
9           10  30.0708

In [126]:
pd.cut(df1['Fare'],bins=2) #bins=n 分为n段区间，起始值、结束值是所有数据的最大值、最小值

0     (7.186, 39.267]
1    (39.267, 71.283]
2     (7.186, 39.267]
3    (39.267, 71.283]
4     (7.186, 39.267]
5     (7.186, 39.267]
6    (39.267, 71.283]
7     (7.186, 39.267]
8     (7.186, 39.267]
9     (7.186, 39.267]
Name: Fare, dtype: category
Categories (2, interval[float64, right]): [(7.186, 39.267] < (39.267, 71.283]]

In [127]:
pd.cut(df1['Fare'],bins=2).value_counts()

Fare
(7.186, 39.267]     7
(39.267, 71.283]    3
Name: count, dtype: int64

In [128]:
pd.cut(df1['Fare'],bins=[0,30,60,90]) #bins=List,分成n段区间

0     (0, 30]
1    (60, 90]
2     (0, 30]
3    (30, 60]
4     (0, 30]
5     (0, 30]
6    (30, 60]
7     (0, 30]
8     (0, 30]
9    (30, 60]
Name: Fare, dtype: category
Categories (3, interval[int64, right]): [(0, 30] < (30, 60] < (60, 90]]

In [129]:
pd.cut(df1['Fare'],bins=[0,30,60,90]).value_counts()

Fare
(0, 30]     6
(30, 60]    3
(60, 90]    1
Name: count, dtype: int64

In [135]:
df1['票价范围']=pd.cut(df1['Fare'],bins=[0,30,60,90],labels=['低','中','高'])
print(df1)

   PassengerId     Fare 收入范围 票价范围
0            1   7.2500    低    低
1            2  71.2833    高    高
2            3   7.9250    低    低
3            4  53.1000    中    中
4            5   8.0500    低    低
5            6   8.4583    低    低
6            7  51.8625    中    中
7            8  21.0750    低    低
8            9  11.1333    低    低
9           10  30.0708    中    中

In [136]:
pd.qcut(df1['Fare'],3)

0      (7.249, 8.458]
1    (30.071, 71.283]
2      (7.249, 8.458]
3    (30.071, 71.283]
4      (7.249, 8.458]
5      (7.249, 8.458]
6    (30.071, 71.283]
7     (8.458, 30.071]
8     (8.458, 30.071]
9     (8.458, 30.071]
Name: Fare, dtype: category
Categories (3, interval[float64, right]): [(7.249, 8.458] < (8.458, 30.071] < (30.071, 71.283]]

In [137]:
pd.qcut(df1['Fare'],3).value_counts()

Fare
(7.249, 8.458]      4
(8.458, 30.071]     3
(30.071, 71.283]    3
Name: count, dtype: int64

In [138]:
df['Sex']=df['Sex'].astype('category')
df['Sex'].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

字符串-->类别-->统计
数值-->分箱-->统计

In [140]:
df['Fare']=pd.cut(df['Fare'],bins=3) #将Fare从int64变为字符串
print(df['Sex'].dtype)
print(df['Fare'].dtype)

category
category

In [156]:
#df.rename()   df.set_index()   df.reset_index()
df=pd.DataFrame({
    'name':['A','B','C','D'],
    'age':[26,25,30,50],
    'gender':['female','male','male','female']
})
print(df)
print('-'*30)
print(df.set_index("name"))
print('-'*30)
df.set_index("name",inplace=True) #inplace直接在原数据上进行修改
print(df)
print('-'*30)
df.reset_index(inplace=True)
print(df)
print('-'*30)
df.rename(columns={"age":"年龄"},index={0:4},inplace=True)
print(df)

  name  age  gender
0    A   26  female
1    B   25    male
2    C   30    male
3    D   50  female
------------------------------
      age  gender
name
A      26  female
B      25    male
C      30    male
D      50  female
------------------------------
      age  gender
name
A      26  female
B      25    male
C      30    male
D      50  female
------------------------------
  name  age  gender
0    A   26  female
1    B   25    male
2    C   30    male
3    D   50  female
------------------------------
  name  年龄  gender
4    A  26  female
1    B  25    male
2    C  30    male
3    D  50  female

In [159]:
df.index=[1,2,3,4]
df.columns=["姓名","年龄","性别"]
print(df)

  姓名  年龄      性别
1  A  26  female
2  B  25    male
3  C  30    male
4  D  50  female

## 时间数据的处理

In [167]:
import pandas as pd
d=pd.Timestamp('2015-05-02 10:22')
d1=pd.Timestamp('2015-05-02 13:22')
print(d)
print(type(d))
print("年",d.year)
print("月",d.month)
print("日",d.day)
print(d.hour,d.minute,d.second)
print("季度",d.quarter)
print("是否是月底",d.is_month_end)
print("星期",d.day_name())
print("转化为天",d.to_period("D"))
print("转化为天",d1.to_period("D"))
print("转化为季度",d.to_period("Q"))
print("转化为年",d.to_period("Y"))
print("转化为月",d.to_period("M"))
print("转化为周",d.to_period("W"))

2015-05-02 10:22:00
<class 'pandas.Timestamp'>
年 2015
月 5
日 2
10 22 0
季度 2
是否是月底 False
星期 Saturday
转化为天 2015-05-02
转化为天 2015-05-02
转化为季度 2015Q2
转化为年 2015
转化为月 2015-05
转化为周 2015-04-27/2015-05-03

In [169]:
# 字符串转换为日期类型
a=pd.to_datetime('2015-02-28 10:22')
print(a)
print(type(a))
print(a.day_name())

2015-02-28 10:22:00
<class 'pandas.Timestamp'>
Saturday

In [176]:
# dataFrame日期转换
df=pd.DataFrame({
    'sales':[100,200,300],
    'date':['20250601','20250602','20250603']
})
df['datetime']=pd.to_datetime(df['date'])
print(df)
print('-'*30)
print(df.info()) #查看表格整体信息，看每列数据类型、有无空值
print('-'*30)
print(type(df['datetime']))
df['week']=df['datetime'].dt.day_name() #因为类型为Series，所以要加dt.进行转换
print(df['week'])
print('-'*30)
print(df['datetime'].dt.year)

   sales      date   datetime
0    100  20250601 2025-06-01
1    200  20250602 2025-06-02
2    300  20250603 2025-06-03
------------------------------
<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   sales     3 non-null      int64
 1   date      3 non-null      str
 2   datetime  3 non-null      datetime64[us]
dtypes: datetime64[us](1), int64(1), str(1)
memory usage: 204.0 bytes
None
------------------------------
<class 'pandas.Series'>
0     Sunday
1     Monday
2    Tuesday
Name: week, dtype: str
------------------------------
0    2025
1    2025
2    2025
Name: datetime, dtype: int32

## 分组聚合

In [185]:
#df.groupby('分组的字段')['聚合的字段'].聚合函数()
import pandas as pd
df=pd.read_csv('titanic.csv')
df['Pclass']=df['Pclass'].astype('int64')
#计算不同Pclass的评价Fare
df.groupby('Pclass').groups #查看分组

{1: [1, 3, 6, 11, 23, 27, 30, 31, 34, 35, 52, 54, 55, 61, 62, 64, 83, 88, 92, 96, 97, 102, 110, 118, 124, 136, 137, 139, 151, 155, 166, 168, 170, 174, 177, 185, 187, 194, 195, 209, 215, 218, 224, 230, 245, 248, 252, 256, 257, 258, 262, 263, 268, 269, 270, 273, 275, 284, 290, 291, 295, 297, 298, 299, 305, 306, 307, 309, 310, 311, 318, 319, 325, 329, 331, 332, 334, 336, 337, 339, 341, 351, 356, 366, 369, 370, 373, 375, 377, 380, 383, 390, 393, 412, 430, 434, 435, 438, 445, 447, ...], 2: [9, 15, 17, 20, 21, 33, 41, 43, 53, 56, 58, 66, 70, 72, 78, 84, 98, 99, 117, 120, 122, 123, 133, 134, 135, 144, 145, 148, 149, 150, 161, 178, 181, 183, 190, 191, 193, 199, 211, 213, 217, 219, 221, 226, 228, 232, 234, 236, 237, 238, 239, 242, 247, 249, 259, 265, 272, 277, 288, 292, 303, 308, 312, 314, 316, 317, 322, 323, 327, 340, 342, 343, 344, 345, 346, 357, 361, 385, 387, 389, 397, 398, 399, 405, 407, 413, 416, 417, 418, 426, 427, 432, 437, 439, 440, 443, 446, 450, 458, 463, ...], 3: [0, 2, 4, 5, 7, 8, 10, 12, 13, 14, 16, 18, 19, 22, 24, 25, 26, 28, 29, 32, 36, 37, 38, 39, 40, 42, 44, 45, 46, 47, 48, 49, 50, 51, 57, 59, 60, 63, 65, 67, 68, 69, 71, 73, 74, 75, 76, 77, 79, 80, 81, 82, 85, 86, 87, 89, 90, 91, 93, 94, 95, 100, 101, 103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114, 115, 116, 119, 121, 125, 126, 127, 128, 129, 130, 131, 132, 138, 140, 141, 142, 143, 146, 147, 152, 153, 154, 156, 157, 158, 159, ...]}

In [187]:
print(df.groupby('Pclass').get_group(1)) #查看具体的某个分组数据

     PassengerId  Survived  Pclass  \
1              2         1       1
3              4         1       1
6              7         0       1
11            12         1       1
23            24         1       1
..           ...       ...     ...
871          872         1       1
872          873         0       1
879          880         1       1
887          888         1       1
889          890         1       1

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
6                              McCarthy, Mr. Timothy J    male  54.0      0
11                            Bonnell, Miss. Elizabeth  female  58.0      0
23                        Sloper, Mr. William Thompson    male  28.0      0
..                                                 ...     ...   ...    ...
871   Beckwith, Mrs. Richard Leonard (Sallie Monypeny)  female  47.0      1
872                           Carlsson, Mr. Frans Olof    male  33.0      0
879      Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)  female  56.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
889                              Behr, Mr. Karl Howell    male  26.0      0

     Parch    Ticket     Fare        Cabin Embarked
1        0  PC 17599  71.2833          C85        C
3        0    113803  53.1000         C123        S
6        0     17463  51.8625          E46        S
11       0    113783  26.5500         C103        S
23       0    113788  35.5000           A6        S
..     ...       ...      ...          ...      ...
871      1     11751  52.5542          D35        S
872      0       695   5.0000  B51 B53 B55        S
879      1     11767  83.1583          C50        C
887      0    112053  30.0000          B42        S
889      0    111369  30.0000         C148        C

[216 rows x 12 columns]

In [194]:
df.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

单层['列名']-->Series
双层[['列名']]-->DataFrame

In [195]:
df2=df.groupby('Pclass')[['Fare']].mean()
df2['Fare']=df2['Fare'].round(2) #round(2)保留两位小数点
print(df2)

         Fare
Pclass
1       84.15
2       20.66
3       13.68

In [206]:
#df2=df2.reset_index()
print(df2.sort_values('Fare',ascending=False)) #从高到低

   level_0  index  Pclass   Fare
0        0      0       1  84.15
1        1      1       2  20.66
2        2      2       3  13.68

In [213]:
# 根据多个条件分组
df2=df.groupby(['Pclass','Sex'])[['Fare']].mean()
df2=df2.reset_index()
df2['Fare']=df2['Fare'].round(2)
print(df2)

   Pclass     Sex    Fare
0       1  female  106.13
1       1    male   67.23
2       2  female   21.97
3       2    male   19.74
4       3  female   16.12
5       3    male   12.66